language: c
sudo: required
dist: trusty    # Ubuntu 14.04
env:
  - TOOLCHAIN=debian
  - TOOLCHAIN=devkitppc
    DEVKITPRO=/home/travis/devkitPro
    DEVKITPPC=/home/travis/devkitPro/devkitPPC
    DEVKITARM=/home/travis/devkitPro/devkitARM
install:
  - .travis/install.sh
script:
  - make
  - ls -lh linux.elf
  - readelf -l linux.elf
