#!/bin/sh

VERSION=`git describe --always --abbrev=12`
if [ -z "$VERSION" ]; then VERSION=unknown; fi

cat << __EOF__
/* This file was automatically generated by version.c.sh */

#include "version.h"

const char program_version[] = "$VERSION";
__EOF__
